# Generated by Django 5.1 on 2024-08-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppId',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.CharField(max_length=255, unique=True)),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
