version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=AmIrMaHdI
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase-arm64
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase.db
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=postgres
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=AmIrMaHdI
      - MB_DB_HOST=postgres
    depends_on:
      - postgres

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=AmIrMaHdI
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - postgres
    volumes:
      - ./api:/app

  crawler:
      build:
        context: ./crawler
        dockerfile: Dockerfile
      container_name: crawler
      volumes:
        - ./crawler:/app
      depends_on:
        - postgres
        - redis
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
volumes:
  metabase_data:
  postgres_data: